import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import worker from '../server/worker.mjs';
import {normalProject,applyEdits,DEFAULT_LAYERS} from '../server/level-model.mjs';
const require=createRequire(import.meta.url),{database}=require('../server/local-db.cjs');
const db=database(':memory:',fileURLToPath(new URL('../drizzle',import.meta.url)));
const env={DB:db};
const room={id:'room1',type:'room',name:'Main',x:0,y:0,w:12,h:10,height:3};
const project={version:1,name:'MCP test level',layers:DEFAULT_LAYERS,objects:[room],grid:1};
async function rpc(method,params={},user='owner'){const headers={'Content-Type':'application/json',Accept:'application/json, text/event-stream'};if(user)headers['oai-authenticated-user-id']=user;const response=await worker.fetch(new Request('https://blockout.test/mcp',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})}),env);return {status:response.status,data:await response.json()};}
async function tool(name,args={},user='owner'){return rpc('tools/call',{name,arguments:args},user);}
test('MCP initializes and discovers tools without disclosing user project data',async()=>{const init=await rpc('initialize',{protocolVersion:'2025-06-18',capabilities:{},clientInfo:{name:'test',version:'1'}});assert.equal(init.data.result.protocolVersion,'2025-06-18');const listing=await rpc('tools/list',{},null);assert.equal(listing.status,200);assert.ok(listing.data.result.tools.some(t=>t.name==='apply_level_edits'));assert.equal(JSON.stringify(listing.data).includes('MCP test level'),false);const denied=await tool('list_level_projects',{},null);assert.equal(denied.status,401);});
test('Authenticated map generation persists an editable project and enforces user ownership',async()=>{const created=await tool('create_level_project',{name:project.name,objects:project.objects});const value=created.data.result.structuredContent;assert.equal(value.revision,1);assert.ok(value.editor_url.endsWith('?project='+value.id));const read=await tool('get_level_project',{project_id:value.id});assert.equal(read.data.result.structuredContent.project.objects[0].w,12);const foreign=await tool('get_level_project',{project_id:value.id},'other-user');assert.equal(foreign.data.result.isError,true);assert.match(foreign.data.result.content[0].text,/not found/i);const list=await tool('list_level_projects',{},'other-user');assert.equal(list.data.result.structuredContent.projects.length,0);});
test('Edit batches are atomic and stale revisions cannot overwrite another edit',async()=>{const created=(await tool('create_level_project',{name:'Atomic level',objects:[room]})).data.result.structuredContent;const invalid=await tool('apply_level_edits',{project_id:created.id,expected_revision:1,update:[{id:'room1',w:20}],add:[{type:'room',name:'Bad',x:0,y:0,w:-5,h:3}]});assert.equal(invalid.data.result.isError,true);const read=(await tool('get_level_project',{project_id:created.id})).data.result.structuredContent;assert.equal(read.revision,1);assert.equal(read.project.objects[0].w,12);const valid=await tool('apply_level_edits',{project_id:created.id,expected_revision:1,update:[{id:'room1',w:20}]});assert.equal(valid.data.result.structuredContent.revision,2);const stale=await tool('apply_level_edits',{project_id:created.id,expected_revision:1,remove:['room1']});assert.equal(stale.data.result.isError,true);assert.match(stale.data.result.content[0].text,/revision conflict/i);});
test('Browser save API shares the same documents, rejects missing identity and checks origin',async()=>{const created=(await tool('create_level_project',{name:'Browser level',objects:[room]})).data.result.structuredContent;const response=await worker.fetch(new Request('https://blockout.test/api/projects/'+created.id,{headers:{'oai-authenticated-user-id':'owner'}}),env);assert.equal((await response.json()).project.name,'Browser level');const anonymous=await worker.fetch(new Request('https://blockout.test/api/projects'),env);assert.equal(anonymous.status,401);const crossOrigin=await worker.fetch(new Request('https://blockout.test/mcp',{method:'POST',headers:{Origin:'https://evil.test','Content-Type':'application/json'},body:'{}'}),env);assert.equal(crossOrigin.status,403);});
test('Moving routes and walls preserves their shape; locked layers reject the entire batch',()=>{const p=normalProject({...project,objects:[{id:'route1',type:'path',name:'Route',x:0,y:0,points:[{x:0,y:0},{x:4,y:3}]},{id:'wall1',type:'wall',name:'Wall',x:1,y:1,x2:8,y2:1}]});const moved=applyEdits(p,{update:[{id:'route1',x:2,y:1},{id:'wall1',x:3,y:2}]});assert.deepEqual(moved.objects[0].points,[{x:2,y:1},{x:6,y:4}]);assert.equal(moved.objects[1].x2,10);assert.equal(moved.objects[1].y2,2);p.layers.find(l=>l.id==='geometry').locked=true;assert.throws(()=>applyEdits(p,{update:[{id:'wall1',x:8}],remove:['route1']}),/locked/);assert.equal(p.objects.length,2);});
test('Malformed JSON, unknown methods and notifications follow JSON-RPC semantics',async()=>{const invalid=await worker.fetch(new Request('https://blockout.test/mcp',{method:'POST',headers:{'Content-Type':'application/json'},body:'{'}),env);assert.equal((await invalid.json()).error.code,-32700);const unknown=await rpc('unknown');assert.equal(unknown.data.error.code,-32601);const notification=await worker.fetch(new Request('https://blockout.test/mcp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',method:'notifications/initialized'})}),env);assert.equal(notification.status,202);});
